version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: usersdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres_password
      DB_NAME: usersdb
      DB_PORT: 5432
      PORT: 5000

volumes:
  pgdata:
